[project]
name = "shiksha-sathi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "absl-py>=2.3.1",
    "dotenv>=0.9.9",
    "google-adk>=1.6.1",
    "google-genai>=1.25.0",
]
